name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 * * * *"   # Runs every hour
  workflow_dispatch:       # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Stats
        uses: anuraghazra/github-readme-stats@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          username: QuanHoangNgoc
          commit: true
          output_dir: ./generated
