name: Generate Simple GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  github-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download GitHub stats card
        run: |
          curl -o github-stats.svg "https://github-readme-stats.vercel.app/api?username=QuanHoangNgoc&show_icons=true&theme=default&hide_border=false"

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add github-stats.svg
          git commit -m "Update simple GitHub stats image" || echo "No changes"
          git push
